name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  go_router: ^10.0.0
  internet_connection_checker_plus: ^2.0.0
  json_annotation: ^4.8.1
  shake: ^2.2.0
  simple_animations: ^5.0.2
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
